-- ═══════════════════════════════════════════════════════════════════════════
-- Industry intelligence for the full controlled vocabulary
--
-- Before this, industry_intelligence held two industries (law, technology) keyed
-- by loose lowercase names, and only 2 of 10 generators consulted it. This
-- re-keys the existing rows onto the controlled INDUSTRIES vocabulary in
-- _shared/industries.ts and seeds the remaining thirteen.
--
-- ── Sourcing ───────────────────────────────────────────────────────────────
-- source_name and source_url are NOT NULL on this table by design: these rows
-- are fed to the model as researched fact, and a claim a student acts on
-- ("you must hold NMBI registration") has to be traceable to the body that
-- actually says it. Every row below is attributed to the regulator,
-- professional body, or statute that is the primary authority for the claim —
-- not to a blog summarising it.
--
-- Statements of hard requirement (registration, statutory titles, vetting) were
-- checked against the issuing body before being written here. Where a
-- requirement is a criminal offence to breach rather than merely expected, the
-- row says so — the Building Control Act 2007 rows are the clearest example,
-- and are stronger than "registration is expected" would have been.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Re-key the two existing industries onto the controlled vocabulary ──────
update public.industry_intelligence set industry = 'Technology and Software' where industry = 'technology';
update public.industry_intelligence set industry = 'Law'                     where industry = 'law';

-- Same for the example library, so both tables share one vocabulary.
update public.example_library set industry = 'Technology and Software'       where industry = 'technology';
update public.example_library set industry = 'Law'                           where industry = 'law';
update public.example_library set industry = 'Healthcare and Nursing'        where industry = 'healthcare';
update public.example_library set industry = 'Finance and Accounting'        where industry = 'finance';
update public.example_library set industry = 'Business and Management'       where industry = 'business';
update public.example_library set industry = 'Education and Teaching'        where industry = 'education';
update public.example_library set industry = 'Hospitality and Tourism'       where industry = 'hospitality';
update public.example_library set industry = 'Marketing and Communications'  where industry = 'marketing';

-- Guard against re-seeding on a database that already ran this migration.
delete from public.industry_intelligence
 where industry in (
   'Engineering', 'Healthcare and Nursing', 'Finance and Accounting',
   'Education and Teaching', 'Business and Management', 'Creative and Media',
   'Science and Research', 'Construction and Architecture', 'Hospitality and Tourism',
   'Public Sector and Civil Service', 'Social Work and Community',
   'Sports and Fitness', 'Marketing and Communications'
 );

insert into public.industry_intelligence (industry, dimension, content, source_name, source_url) values

-- ═══════════════ ENGINEERING ═══════════════
('Engineering', 'screening_mechanism', 'Engineers Ireland operates the Registered Professional Titles — Engineering Technician, Associate Engineer, and Chartered Engineer (CEng). Chartered assessment has two phases: Phase 1 educational formation (since 2013 a Level 9 Master of Engineering satisfies this) and Phase 2 initial professional development, demonstrated through applied working competence. Graduate engineering roles at large Irish employers screen for membership or a stated intention to work toward CEng, alongside ATS keyword scanning for named technical tools.', 'Engineers Ireland — Registered Professional Titles', 'https://www.engineersireland.ie/Professionals/Membership/Registered-professional-titles'),
('Engineering', 'must_have', 'A degree in the relevant engineering discipline, and software named with real specificity. "Experience with design software" fails where "AutoCAD, Civil 3D and Revit, used across a 9-month placement" passes. Placement, co-op, or internship experience with quantified outcomes is the single strongest graduate signal. Engineers Ireland student or graduate membership where held.', 'Engineers Ireland — Chartered Engineer application guidance', 'https://www.engineersireland.ie/Professionals/Membership/Registered-professional-titles/Chartered-Engineer'),
('Engineering', 'red_flag', 'Vague technology claims with no tool named. No technical skills section at all on a CV for a technical role. Claiming or implying Chartered Engineer status without being on the register — CEng is a registered professional title, and asserting it unearned is checkable and disqualifying.', 'Engineers Ireland — Registered Professional Titles', 'https://www.engineersireland.ie/Professionals/Membership/Registered-professional-titles'),
('Engineering', 'wording_convention', 'Lead with the discipline and the tool, then the outcome. Engineering reviewers read for evidence of applied competence rather than responsibility held, so "reduced hydraulic model runtime 40% by restructuring the Civil 3D surface" carries further than "responsible for hydraulic modelling".', 'Engineers Ireland — Chartered Engineer competence framework (Phase 2)', 'https://www.engineersireland.ie/Professionals/Membership/Registered-professional-titles/Chartered-Engineer'),
('Engineering', 'real_entity', 'Engineers Ireland (professional body and registration authority), ESB Networks, EirGrid, Uisce Éireann (Irish Water), Transport Infrastructure Ireland, Intel Ireland (Leixlip), Apple Cork, Boston Scientific (Galway, Clonmel, Cork), Medtronic (Galway), Abbott, Pfizer Ringaskiddy, Analog Devices Limerick, Construction Industry Federation, SEAI, IDA Ireland.', 'Engineers Ireland — Registered Professional Titles', 'https://www.engineersireland.ie/Professionals/Membership/Registered-professional-titles'),

-- ═══════════════ HEALTHCARE AND NURSING ═══════════════
('Healthcare and Nursing', 'screening_mechanism', 'Registration with NMBI is a legal requirement to practise nursing or midwifery in Ireland — on approval NMBI issues a Personal Identification Number (PIN) which is the licence to practise, renewed annually with a retention fee. For Irish-qualified applicants from an approved programme processing typically takes four to eight weeks; overseas qualifications take longer. Allied health professions — physiotherapy, occupational therapy, speech and language therapy, social care, radiography, dietetics and others — are regulated separately by CORU, which runs a registration board per profession. HSE roles are recruited through a structured competency application rather than CV-first screening.', 'NMBI / CORU — statutory registration requirements', 'https://www.nmbi.ie/Registration'),
('Healthcare and Nursing', 'must_have', 'An NMBI PIN for nursing and midwifery roles, or CORU registration for the regulated allied health professions — or documented evidence that an application is in progress if newly qualified. Clinical placement described with setting, hours, and patient population. Mandatory training evidenced by name: Basic Life Support, manual handling, safeguarding / Children First. Named clinical skills rather than "clinical experience".', 'CORU — Health and Social Care Professionals registration', 'https://www.coru.ie/health-and-social-care-professionals/'),
('Healthcare and Nursing', 'red_flag', 'No registration number and no statement that registration is pending — for a role where registration is a legal precondition this is not a gap, it is a disqualification. Clinical experience described without setting or skills. Missing mandatory training. A personal statement with no articulated approach to patient care.', 'NMBI — Registration', 'https://www.nmbi.ie/Registration'),
('Healthcare and Nursing', 'wording_convention', 'Clinical writing is precise and non-promotional. Name the setting, the patient group, the intervention, and the multidisciplinary context — "supported a caseload of 12 post-operative patients on a 28-bed surgical ward, working within the MDT" reads as competence; "passionate about delivering excellent patient care" reads as filler.', 'CORU — Standards of Proficiency', 'https://www.coru.ie/health-and-social-care-professionals/'),
('Healthcare and Nursing', 'real_entity', 'NMBI (Nursing and Midwifery Board of Ireland), CORU, HSE, Children''s Health Ireland (Crumlin, Temple Street), St Vincent''s University Hospital, Beaumont Hospital, St James''s Hospital, Mater Misericordiae, Cork University Hospital, University Hospital Galway, Tusla, Enable Ireland, Rehab Group, Brothers of Charity, Irish Society of Chartered Physiotherapists.', 'CORU — registration boards', 'https://www.coru.ie/about-us/registration-boards/'),

-- ═══════════════ FINANCE AND ACCOUNTING ═══════════════
('Finance and Accounting', 'screening_mechanism', 'The ACA with Chartered Accountants Ireland is a graduate-level qualification completed over roughly 3.5 years through a training contract with an Authorised Training Employer (ATE), with exams at CAP1, CAP2 and FAE levels. Accredited Irish accounting degrees carry pre-approved exemptions from CAP1 and sometimes CAP2; certain accounting Masters and PG Diplomas are pre-approved to exempt two full exam levels, leaving only FAE. The Big 4 and the main Irish banks screen with online assessments — numerical reasoning, situational judgement, verbal reasoning — before or alongside CV review. Spring weeks and insight days are the main first- and second-year entry route.', 'Chartered Accountants Ireland — Training Contract and Flexible Route pathways', 'https://becomeacharteredaccountant.com/wp-content/uploads/2022/07/TC-FR-pathways-web.pdf'),
('Finance and Accounting', 'must_have', 'Qualification pathway stated explicitly: which body (ACA, ACCA, CIMA), which exemptions held, which exams passed or scheduled. Numerical capability evidenced by something concrete rather than asserted. Any insight day, spring week, or virtual internship named. Regulatory awareness for financial services roles — Central Bank of Ireland, MiFID II, GDPR in a financial context.', 'Chartered Accountants Ireland — exemptions and pathways', 'https://becomeacharteredaccountant.com/wp-content/uploads/2022/07/TC-FR-pathways-web.pdf'),
('Finance and Accounting', 'red_flag', 'No qualification pathway mentioned at all in an accountancy application. "Strong numerical skills" with nothing behind it. Applying to a Big 4 firm with no evidence of commercial awareness — no view on the firm''s market, clients, or recent developments. Confusing the bodies or the exam structure, which signals no research was done.', 'Chartered Accountants Ireland', 'https://www.charteredaccountants.ie/'),
('Finance and Accounting', 'wording_convention', 'Quantify or do not claim. Finance reviewers read for scale, accuracy and control — "reconciled a 400-line monthly ledger with a 3-day close" beats "assisted with month-end". Commercial awareness is demonstrated by a specific observation about a specific business, never by the phrase "commercially aware".', 'Chartered Accountants Ireland — ACA qualification', 'https://www.charteredaccountants.ie/'),
('Finance and Accounting', 'real_entity', 'Chartered Accountants Ireland, ACCA, CIMA, Central Bank of Ireland, Deloitte Ireland, PwC Ireland, EY Ireland, KPMG Ireland, Grant Thornton, Mazars, AIB, Bank of Ireland, PTSB, Davy, Goodbody, Irish Funds, IFSC Dublin, Financial Services Ireland, Revenue Commissioners.', 'Chartered Accountants Ireland', 'https://www.charteredaccountants.ie/'),

-- ═══════════════ EDUCATION AND TEACHING ═══════════════
('Education and Teaching', 'screening_mechanism', 'Registration with the Teaching Council is a legal precondition for teaching in a recognised school in Ireland, and is required for payment from the Department of Education. Primary teaching requires a Bachelor of Education or a Professional Master of Education (PME); post-primary requires a degree with recognised subject specialisation plus a PME. Droichead is the induction process for newly qualified teachers and is the only route of induction for teachers registered after 1 June 2020 — primary NQTs complete a minimum block of 60 consecutive school days, post-primary a minimum of 200 hours'' teaching employment in an eligible setting. Garda vetting is mandatory.', 'The Teaching Council — Registration Handbook 2025/2026', 'https://www.teachingcouncil.ie/assets/uploads/2025/05/00.-Final-Version_-The-Teaching-Council-Registration-Handbook-2025-2026_English.pdf'),
('Education and Teaching', 'must_have', 'Teaching Council registration number, or the registration route being applied under. B.Ed or PME named with the awarding institution. Subject specialisation for post-primary. School placement described with school type, year groups, and subjects taught. Garda vetting status. Droichead status for NQTs.', 'The Teaching Council — Droichead', 'https://www.teachingcouncil.ie/i-am-a-registered-teacher/registration-with-conditions/droichead/'),
('Education and Teaching', 'red_flag', 'No Teaching Council reference on an application for a recognised school post. No school placement evidence. A personal statement with no articulated classroom philosophy and no reference to differentiation, assessment, or inclusion — the three things Irish school leaders read for.', 'The Teaching Council — Registration Handbook', 'https://www.teachingcouncil.ie/assets/uploads/2025/05/00.-Final-Version_-The-Teaching-Council-Registration-Handbook-2025-2026_English.pdf'),
('Education and Teaching', 'wording_convention', 'Write from the pupil outcome backwards. "Introduced a station-teaching model for a mixed-ability 4th class, which moved six pupils off the SEN support list by year end" evidences practice; "excellent classroom management skills" does not. Use the Irish vocabulary correctly — Junior Cycle, Senior Cycle, SEN, SNA, Aistear, Croke Park hours.', 'The Teaching Council — Registration Handbook', 'https://www.teachingcouncil.ie/assets/uploads/2025/05/00.-Final-Version_-The-Teaching-Council-Registration-Handbook-2025-2026_English.pdf'),
('Education and Teaching', 'real_entity', 'The Teaching Council of Ireland, Department of Education, Education and Training Boards (ETBs), PDST, Junior Cycle for Teachers (JCT), INTO, ASTI, TUI, NCSE, NCCA, Scoilnet, Educate Together, An Foras Pátrúnachta.', 'The Teaching Council', 'https://www.teachingcouncil.ie/'),

-- ═══════════════ BUSINESS AND MANAGEMENT ═══════════════
('Business and Management', 'screening_mechanism', 'Graduate programmes at large Irish employers run structured competency screening, usually with an online application, psychometric or situational judgement testing, and an assessment centre. Commercial awareness specific to the employer — its market position, recent results, competitors — is the primary differentiator at interview and in cover letters. Leadership evidence from society committees, club roles, or part-time work carries real weight at graduate level because it is the only leadership most applicants have.', 'gradireland — graduate recruitment in Ireland', 'https://gradireland.com/'),
('Business and Management', 'must_have', 'Evidence of commercial awareness tied to the specific organisation, not the sector in general. Leadership or initiative with a concrete outcome. Data literacy named — Excel to a stated level, Power BI, Tableau, SQL. Any society committee role, enterprise competition, or startup involvement.', 'gradireland — graduate recruitment in Ireland', 'https://gradireland.com/'),
('Business and Management', 'red_flag', 'A cover letter that would work for any employer in the sector. "Microsoft Office" listed as a skill with no level or application. Claiming interest in a company with nothing specific about it. Leadership claimed with no situation attached.', 'gradireland — graduate recruitment in Ireland', 'https://gradireland.com/'),
('Business and Management', 'wording_convention', 'Business reviewers read for commercial consequence. Frame achievements as decision, action, result, with a number wherever one honestly exists — "restructured the society''s sponsorship approach and grew income from €900 to €4,200 across one academic year" rather than "responsible for sponsorship".', 'gradireland — graduate recruitment in Ireland', 'https://gradireland.com/'),
('Business and Management', 'real_entity', 'Ibec, Enterprise Ireland, IDA Ireland, Local Enterprise Offices, InterTradeIreland, Bord Bia, Fáilte Ireland, CRH, Kerry Group, Glanbia, Smurfit Westrock, Ryanair, Aer Lingus, Diageo Ireland, Irish Life, ESB, CPL, Musgrave Group, Dunnes Stores, Penneys/Primark.', 'Enterprise Ireland', 'https://www.enterprise-ireland.com/'),

-- ═══════════════ CREATIVE AND MEDIA ═══════════════
('Creative and Media', 'screening_mechanism', 'For most creative roles the portfolio is the screen and the CV is secondary — an application without a portfolio link is frequently not assessed at all. Portfolios are judged on curation rather than volume: a tight set of six strong pieces outperforms twenty mixed ones, because the weakest piece sets the perceived ceiling. For journalism and editorial, published clips serve the same function. Screen and broadcast roles additionally screen for credited work and crew references.', 'Screen Ireland — careers and production', 'https://www.screenireland.ie/'),
('Creative and Media', 'must_have', 'A portfolio or clips link in the CV header, not buried at the end. Software named specifically — Adobe Creative Suite by application, Figma, Final Cut Pro, DaVinci Resolve, After Effects. Published, exhibited, broadcast or commercially used work named. Client or brand names where the work was real and non-confidential.', 'Design & Crafts Council Ireland', 'https://www.dcci.ie/'),
('Creative and Media', 'red_flag', 'No portfolio link. Describing creative work in the abstract without naming a single piece. Software listed as proficiency with nothing produced in it visible anywhere. An uncurated portfolio that includes student exercises alongside professional work without distinction.', 'Screen Ireland', 'https://www.screenireland.ie/'),
('Creative and Media', 'wording_convention', 'Let the work carry the claim. Creative reviewers distrust adjectives and trust artefacts, so describe the brief, the constraint, and the outcome — "rebranded a 40-year-old Cork food producer across packaging and web within an existing colour system" beats "creative and innovative designer".', 'Design & Crafts Council Ireland', 'https://www.dcci.ie/'),
('Creative and Media', 'real_entity', 'Design & Crafts Council Ireland, Screen Ireland, Arts Council of Ireland, RTÉ, Virgin Media Television, TG4, Newstalk, Today FM, The Irish Times, Irish Independent, Business Post, NCAD, IADT Dún Laoghaire, TU Dublin School of Media, Windmill Lane, Brown Bag Films, Cartoon Saloon.', 'Screen Ireland', 'https://www.screenireland.ie/'),

-- ═══════════════ SCIENCE AND RESEARCH ═══════════════
('Science and Research', 'screening_mechanism', 'Academic and research roles screen on outputs — publications, conference presentations, and poster sessions — and on named technique competence. Industry science roles in the Irish pharma and medtech cluster screen additionally for GMP (Good Manufacturing Practice) exposure and regulatory literacy, since manufacturing sites operate under HPRA and EMA oversight and untrained staff cannot work in a GMP area without documented training.', 'Health Products Regulatory Authority (HPRA)', 'https://www.hpra.ie/'),
('Science and Research', 'must_have', 'Laboratory techniques named individually — PCR, ELISA, Western blot, HPLC, flow cytometry, cell culture — not "laboratory experience". Statistical and analysis tools named: R, Python, SPSS, GraphPad, MATLAB. Any publication, poster, or conference contribution with the venue. Final year project or thesis described with hypothesis, method, and result. GMP or GLP training for industry roles.', 'Science Foundation Ireland', 'https://www.sfi.ie/'),
('Science and Research', 'red_flag', 'Generic "laboratory experience" with no technique named. No statistical method mentioned for data-heavy work. Applying to a regulated manufacturer with no reference to GMP, quality systems, or documentation practice. Listing techniques without ever stating what was being investigated.', 'Health Products Regulatory Authority (HPRA)', 'https://www.hpra.ie/'),
('Science and Research', 'wording_convention', 'Method before result, and never overstate significance. Scientific reviewers read for whether the writer understands their own data — "optimised an ELISA protocol, reducing inter-assay CV from 18% to 7% across 30 replicates" evidences rigour; "carried out advanced laboratory research" evidences nothing.', 'Science Foundation Ireland', 'https://www.sfi.ie/'),
('Science and Research', 'real_entity', 'Science Foundation Ireland, Health Research Board, Irish Research Council, HPRA, European Medicines Agency, Teagasc, Tyndall National Institute, APC Microbiome Ireland, Pfizer, MSD, AbbVie, Alexion, Regeneron, Takeda, Janssen, Boston Scientific, Medtronic, Stryker, IDA Ireland.', 'Science Foundation Ireland', 'https://www.sfi.ie/'),

-- ═══════════════ CONSTRUCTION AND ARCHITECTURE ═══════════════
('Construction and Architecture', 'screening_mechanism', 'Under the Building Control Act 2007 it is a criminal offence to use the title "architect", "building surveyor" or "quantity surveyor" without being entered on the relevant statutory register. Those registers are operated by the RIAI (architects) and the SCSI (building surveyors and quantity surveyors), and entry requires an accredited qualification plus the training and experience the Act specifies. This makes title accuracy a screening issue before competence is even assessed. BIM proficiency is increasingly a hard requirement on design and project roles, and Safe Pass is a precondition for any site-based work.', 'Building Control Act 2007 — statutory registration of construction professional titles (SCSI Registration Body)', 'https://scsi.ie/the-register/registration-body/'),
('Construction and Architecture', 'must_have', 'Accurate title use — describe yourself as an architectural graduate or graduate quantity surveyor unless actually on the register. RIAI or SCSI/RICS membership or documented progress toward it. BIM software named: Revit, ArchiCAD, AutoCAD, Navisworks. Safe Pass and any Safety Awareness or CSCS-equivalent cards for site roles. A project list or portfolio with drawings and photographs for design roles.', 'Society of Chartered Surveyors Ireland — Getting on the Register', 'https://scsi.ie/the-register/registration-body/getting-on-the-register/'),
('Construction and Architecture', 'red_flag', 'Using a protected title without registration — legally exposed and immediately checkable against the public register. No BIM reference on a design or project management application. No Safe Pass for a site-based role. No professional body pathway named for a role above graduate level.', 'Building Control Act 2007 — registration bodies', 'https://scsi.ie/the-register/registration-body/'),
('Construction and Architecture', 'wording_convention', 'Anchor everything to project, value, and stage. Construction reviewers read for whether you have worked at the scale they operate at — "assisted cost planning on a €12m residential scheme through RIBA Stages 3–4" places you instantly; "worked on construction projects" does not.', 'Society of Chartered Surveyors Ireland', 'https://scsi.ie/'),
('Construction and Architecture', 'real_entity', 'RIAI (Royal Institute of the Architects of Ireland), SCSI (Society of Chartered Surveyors Ireland), RICS Ireland, Construction Industry Federation, CIRI, Engineers Ireland, Transport Infrastructure Ireland, Office of Public Works, Land Development Agency, Dublin City Council Planning, BAM Ireland, John Sisk & Son, Walls Construction, John Paul Construction, Collen Construction.', 'Society of Chartered Surveyors Ireland — Registration Body', 'https://scsi.ie/the-register/registration-body/'),

-- ═══════════════ HOSPITALITY AND TOURISM ═══════════════
('Hospitality and Tourism', 'screening_mechanism', 'Hospitality hiring is experience-led and venue-specific: which property, what standard, what covers or occupancy, and what section. Star rating and reputation of previous properties function as a proxy for standard, particularly for luxury and fine dining roles. HACCP-based food safety training is a legal requirement for food business staff in Ireland, enforced by the FSAI, so its absence is a compliance problem rather than a preference. Language skills are a direct advantage in visitor-facing tourism roles.', 'Food Safety Authority of Ireland — HACCP and staff training', 'https://www.fsai.ie/'),
('Hospitality and Tourism', 'must_have', 'Establishments named, with standard or star rating where it applies. Scale handled — covers per service, rooms, occupancy, or team size. HACCP or equivalent food safety training for any food handling role. Languages with an honest level. Any Fáilte Ireland programme or industry certification.', 'Fáilte Ireland — industry training and standards', 'https://www.failteireland.ie/'),
('Hospitality and Tourism', 'red_flag', 'Hospitality experience described without naming a single venue. No food safety training referenced for a food service role. Vague "customer service" claims with no volume, standard, or setting. Overstating a role — claiming section responsibility for what was a runner position is quickly exposed by anyone in the trade.', 'Food Safety Authority of Ireland', 'https://www.fsai.ie/'),
('Hospitality and Tourism', 'wording_convention', 'Numbers and standard, plainly stated. "Ran a 14-table section across 120-cover Saturday services in a 4-star property" tells a head chef or GM everything; "provided excellent customer service in a busy restaurant" tells them nothing they can calibrate.', 'Fáilte Ireland', 'https://www.failteireland.ie/'),
('Hospitality and Tourism', 'real_entity', 'Fáilte Ireland, Tourism Ireland, Irish Hotels Federation, Restaurants Association of Ireland, Food Safety Authority of Ireland, Adare Manor, Ashford Castle, Dromoland Castle, The Shelbourne, The Merrion, Dalata Hotel Group, Ryanair, Aer Lingus, Guinness Storehouse, Cliffs of Moher Experience.', 'Fáilte Ireland', 'https://www.failteireland.ie/'),

-- ═══════════════ PUBLIC SECTOR AND CIVIL SERVICE ═══════════════
('Public Sector and Civil Service', 'screening_mechanism', 'The Public Appointments Service runs centralised recruitment for the Civil Service and much of the wider public service, scoring applications against published competency models that differ by grade. At Executive Officer level the headings are Drive & Commitment to Public Service Values, Specialist Knowledge Expertise and Self Development, Delivery of Results, People Management, Analysis & Decision Making, and Interpersonal & Communication Skills. Applications are scored per competency, so an answer that does not address the heading it sits under scores nothing regardless of how strong the story is.', 'Public Appointments Service — Civil Service Competency Model, Executive Officer level', 'https://www.publicjobs.ie/documents/Executive_Officer_Competencies.pdf'),
('Public Sector and Civil Service', 'must_have', 'One structured, specific example per competency heading, written against the heading as published for that grade. Evidence of public service values — impartiality, accountability, service to the citizen. Any prior public, civil, or voluntary service named. Irish language ability where the role attracts it.', 'Public Appointments Service — competency models', 'https://www.publicjobs.ie/documents/Executive_Officer_Competencies.pdf'),
('Public Sector and Civil Service', 'red_flag', 'Private-sector framing with no public value dimension — profit and growth language where accountability and service should be. One generalised answer stretched across several competencies. No reference to the framework at all, which reads as not having opened the published model. Vague "we" narration that never isolates the applicant''s own contribution.', 'Public Appointments Service — Civil Service Competency Model', 'https://www.publicjobs.ie/documents/Executive_Officer_Competencies.pdf'),
('Public Sector and Civil Service', 'wording_convention', 'Answer in the first person singular, against the heading, with a bounded example. Assessors score what you personally did, so "I redesigned the intake form after auditing 200 submissions, cutting incomplete applications by a third" scores where "our team improved the process" does not.', 'Public Appointments Service — competency models', 'https://www.publicjobs.ie/documents/Executive_Officer_Competencies.pdf'),
('Public Sector and Civil Service', 'real_entity', 'Public Appointments Service (publicjobs.ie), Commission for Public Service Appointments, Department of Public Expenditure NDP Delivery and Reform, Department of Finance, Department of Education, Department of Health, Revenue Commissioners, HSE, An Garda Síochána, Defence Forces, Office of Public Works, Local Authorities and County Councils, Citizens Information Board.', 'Public Appointments Service', 'https://www.publicjobs.ie/'),

-- ═══════════════ SOCIAL WORK AND COMMUNITY ═══════════════
('Social Work and Community', 'screening_mechanism', 'CORU registration through the Social Workers Registration Board is a legal requirement to practise as a social worker in Ireland, and the Board approves the qualifications that attest to the required standard of proficiency. Tusla is the primary statutory employer for child protection social work. Garda vetting is mandatory for work with children or vulnerable adults. Recruitment is values-based: panels probe for person-centred practice, anti-discriminatory practice, and use of reflective supervision, rather than task lists.', 'CORU — Social Workers Registration Board', 'https://coru.ie/health-and-social-care-professionals/education/approved-qualifications/social-workers/'),
('Social Work and Community', 'must_have', 'CORU registration or documented progress toward it for any qualified social work post. Garda vetting status. Placement described with population, setting, and statutory context. Evidence of reflective practice and supervision. Children First / safeguarding training named.', 'CORU — Social Workers Registration Board', 'https://coru.ie/health-and-social-care-professionals/education/approved-qualifications/social-workers/'),
('Social Work and Community', 'red_flag', 'No CORU reference on a qualified social work application, where registration is a legal precondition. No placement detail. A personal statement with no values framework and no acknowledgement of power, risk, or boundaries — the three things values-based panels test for.', 'CORU — Social Workers Registration Board', 'https://coru.ie/health-and-social-care-professionals/education/approved-qualifications/social-workers/'),
('Social Work and Community', 'wording_convention', 'Person-first language throughout, and precision about your own role in a multi-agency picture. "Held a caseload of nine children in care, co-working with school completion and CAMHS, and chaired three review meetings" reads as practice-ready; "passionate about helping vulnerable people" does not.', 'CORU — Standards of Proficiency for Social Workers', 'https://coru.ie/health-and-social-care-professionals/education/approved-qualifications/social-workers/'),
('Social Work and Community', 'real_entity', 'CORU (Social Workers Registration Board), IASW, Tusla — Child and Family Agency, HSE Social Care, Oberstown Children Detention Campus, Peter McVerry Trust, Focus Ireland, Barnardos Ireland, ISPCC, Simon Community, Depaul, Enable Ireland, Brothers of Charity, St Vincent de Paul.', 'CORU — registration boards', 'https://www.coru.ie/about-us/registration-boards/'),

-- ═══════════════ SPORTS AND FITNESS ═══════════════
('Sports and Fitness', 'screening_mechanism', 'Qualification and its awarding body are the first screen. NCEF, an academic affiliate of the University of Limerick, awards the Certificate in Exercise & Health Fitness at Level 6 on the NFQ and the Higher Certificate over two years, and is the university-accredited route in Ireland. REPS Ireland operates a register of fitness professionals and maintains the list of approved industry training providers, so an unrecognised certificate is a real screening risk. First aid and CPR currency is expected, and public liability insurance is a practical precondition for self-employed coaching.', 'National Council for Exercise & Fitness (NCEF), University of Limerick', 'https://www.ncef.ie/recognition-within-ireland'),
('Sports and Fitness', 'must_have', 'Qualification named with its awarding body and NFQ level. Current first aid and CPR certification. Sport-specific coaching awards with the governing body that issued them. Client or athlete outcomes where they exist, described honestly. Insurance for self-employed work.', 'NCEF — Academic Recognition', 'https://www.ncef.ie/recognition-within-ireland'),
('Sports and Fitness', 'red_flag', 'A qualification named without its awarding body, which usually means it is not recognised. No first aid certification. Transformation claims with no timeframe or starting point. Coaching methodology described entirely in motivational language with no programming detail.', 'NCEF — Industry Standards', 'https://www.ncef.ie/european-industry-standards'),
('Sports and Fitness', 'wording_convention', 'Programming detail is the credential. "Delivered a 12-week block-periodised strength programme for a panel of 22 minor hurlers, with weekly movement screening" demonstrates competence; "passionate about helping people reach their goals" is what everyone writes.', 'NCEF', 'https://www.ncef.ie/'),
('Sports and Fitness', 'real_entity', 'NCEF (University of Limerick), REPS Ireland, Sport Ireland, Sport Ireland Institute, GAA, IRFU, FAI, Athletics Ireland, Swim Ireland, Basketball Ireland, Paralympics Ireland, UKSCA, NSCA, Setanta College, Dalata and Westwood gym groups, ICON Health Clubs.', 'National Council for Exercise & Fitness', 'https://www.ncef.ie/'),

-- ═══════════════ MARKETING AND COMMUNICATIONS ═══════════════
('Marketing and Communications', 'screening_mechanism', 'Marketing hiring has shifted toward evidence: even at graduate level a small portfolio of campaigns, content, or measurable results separates applicants, and a live link in the application is doing the work a CV bullet cannot. Digital roles screen for named platform competence rather than "digital marketing", and certification through the platforms themselves is cheap enough that its absence is read as lack of initiative. PR roles screen for coverage actually secured; content roles screen for published writing.', 'Marketing Institute of Ireland', 'https://www.mii.ie/'),
('Marketing and Communications', 'must_have', 'Platforms named specifically — Google Analytics 4, Google Ads, Meta Ads Manager, HubSpot, Mailchimp, SEMrush or Ahrefs. Campaign results quantified: reach, engagement rate, conversion, cost per acquisition. Published content, coverage, or campaign links. A platform certification where held.', 'Marketing Institute of Ireland', 'https://www.mii.ie/'),
('Marketing and Communications', 'red_flag', '"Strong communication skills" as a marketing credential. No digital tool named anywhere in a digital marketing application. No portfolio, samples, or coverage links for a content or PR role. Results quoted with no baseline, which reads as either inflated or not understood.', 'Public Relations Institute of Ireland', 'https://www.prii.ie/'),
('Marketing and Communications', 'wording_convention', 'Baseline, intervention, result — in that order, with the platform named. "Grew an Instagram audience from 1,200 to 6,800 over five months through a weekly student-story series, lifting engagement rate from 1.9% to 4.4%" is the standard; percentages without baselines are treated as noise.', 'Marketing Institute of Ireland', 'https://www.mii.ie/'),
('Marketing and Communications', 'real_entity', 'Marketing Institute of Ireland, Public Relations Institute of Ireland, Advertising Standards Authority for Ireland, IAB Ireland, Google Ireland, Meta Ireland, HubSpot Dublin, LinkedIn Dublin, Core Media, Publicis Dublin, Mindshare Ireland, Havas Dublin, Edelman Ireland, Teneo, Thinkhouse.', 'Marketing Institute of Ireland', 'https://www.mii.ie/');

-- ── Technology: the original seed had no wording_convention row ───────────
insert into public.industry_intelligence (industry, dimension, content, source_name, source_url)
select 'Technology and Software', 'wording_convention',
  'Lead the bullet with the technical decision, not the assignment. Engineering reviewers scan for what you built and what constraint you were solving under — "cut API p95 latency from 800ms to 210ms by replacing N+1 queries with a batched loader" is read as evidence; "worked on backend performance" is read as filler. Mirror the exact technology names from the job posting, since ATS match on exact terms rather than synonyms, and never inflate familiarity into proficiency — technical interviews expose it immediately.',
  'ResumeAdapter — software engineer resume keywords (2026 ATS data)',
  'https://www.resumeadapter.com/blog/software-engineer-resume-keywords'
where not exists (
  select 1 from public.industry_intelligence
   where industry = 'Technology and Software' and dimension = 'wording_convention'
);

-- ── Law: fill the gaps the audit flagged against the existing five rows ────
insert into public.industry_intelligence (industry, dimension, content, source_name, source_url)
select 'Law', 'real_entity',
  'Law Society of Ireland (solicitors), The Bar of Ireland and King''s Inns (barristers), Four Courts, Chief State Solicitor''s Office, Office of the Director of Public Prosecutions, Legal Aid Board, FLAC (Free Legal Advice Centres), Arthur Cox, A&L Goodbody, Matheson, McCann FitzGerald, William Fry, Mason Hayes & Curran, Maples Group, Philip Lee, ByrneWallace.',
  'Law Society of Ireland', 'https://www.lawsociety.ie/'
where not exists (
  select 1 from public.industry_intelligence
   where industry = 'Law' and dimension = 'real_entity' and content like '%Arthur Cox%'
);
