-- Foundation Blueprint: Irish national examples, alongside the international/global
-- set already seeded. Sourced from Irish official bodies (publicjobs.ie), Irish
-- graduate careers services (gradireland.com), and Irish job boards (Indeed
-- Ireland) — real and attributed, same standard as the international set.

insert into public.example_library (category, industry, competency_tag, excerpt, why_it_works, source_name, source_url) values
('cv_bullet', 'healthcare', null, 'Attentive and empathetic nurse with over five years experience in the healthcare sector. Committed to the highest levels of patient care and serving the community with compassion and kindness.', 'A real Irish nursing CV summary — pairs a quantified fact (five years) with the values language HSE and private hospital recruiters specifically screen for, rather than generic "hard-working" claims.', 'Indeed Ireland', 'https://ie.indeed.com/career-advice/cvs-cover-letters/nursing-cv'),
('cv_bullet', 'business', null, 'Completed a business consultancy project collaborating with a local SME to improve operational efficiency and strategy alignment', 'Real graduate-level achievement language from Ireland''s own graduate careers authority — shows how academic project work gets framed as a genuine business achievement, not just coursework.', 'gradireland', 'https://gradireland.com/careers-advice/cvs-applications-and-tests/graduate-cv-faqs'),
('cv_bullet', 'hospitality', null, 'Dynamic and motivated professional with over three years of experience in customer service and retail', 'A real Irish CV summary example for the retail/hospitality/customer service sector — one of Ireland''s largest employers of first-time CV writers, so the tone here (energetic, practical) is what actually works for entry-level Irish applications.', 'CareerBldr — CV Writing Guide for Ireland', 'https://careerbldr.com/blog/cv-guide-ireland/'),
('linkedin_headline', 'finance', null, 'Finance Professional | Specializing in Mergers & Acquisitions, Capital Raising, and Portfolio Management | Formerly with BlackRock', 'A real Dublin-based finance headline — shows the same Title|Specialty|Credibility formula holding up in the Irish market specifically, including naming a recognisable former employer as social proof.', 'Resume Worded', 'https://resumeworded.com/linkedin-samples/finance-professional-linkedin-headline-examples'),
('star_answer', 'general', null, 'Official Irish Civil Service guidance: Situation — one or two sentences on where you worked/studied and your role. Task — the problem or challenge and the goal. Action — the specific steps taken, in detail. Result — the outcome, explicitly tied back to the competency being assessed and what was learned. Candidates are advised to build a personal evidence bank of 6-8 strong examples, each mapped to one or more competencies, well before the interview.', 'This is the actual official framework Irish public-sector interviews are scored against — and it independently confirms the evidence-bank approach (6-8 stories, tagged by competency) already built into Application Form Assistance and Interview Preparation is exactly what Ireland''s own recruitment authority recommends.', 'publicjobs.ie — Interview Advice', 'https://www.publicjobs.ie/en/information-hub/our-recruitment-process/interview-advice')
on conflict do nothing;
